import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { ThemeSwitcher } from '@/components/ui/theme-switcher';

const inter = Inter({
  variable: '--font-family-sans',
  subsets: ['latin'],
});

const jetbrainsMono = JetBrains_Mono({
  variable: '--font-family-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}>
        <div>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div>
              {children}
              <div className="fixed bottom-4 right-4">
                <ThemeSwitcher />
              </div>
            </div>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
